djangoTinyURL/djangoTinyURL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tinyurl/', include('tinyurl.urls')),
    path('admin/', admin.site.urls),
]

djangoTinyURL/tinyurl/urls.py
from django.urls import path

from . import views

app_name = 'tinyurl'
urlpatterns = [
    # /tinyurl/
    path('', views.IndexView.as_view(), name='index'),
    # /tinyurl/4/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # /tinyurl/create/
    path('create/', views.create, name='create'),
    # /tinyurl/create_post/
    path('create_post/', views.create_post, name='create_post'),
    # /tinyurl/:3/some_hash
    path(':3/<my_hash>', views.tiny_url, name='tiny_url'),
    # /tinyurl/delete/
    path('delete/', views.delete, name='delete'),
]

djangoTinyURL/tinyurl/models.py
from django.db import models
from django.urls import reverse


def get_tiny_url_page_url():
    c = '*'
    return 'http://127.0.0.1:8000' + reverse('tinyurl:tiny_url', args=(c, )).strip(c)


class MyUrl(models.Model):
    original_url = models.CharField(max_length=200)
    hash = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    last_us_date = models.DateTimeField('date of last using of url')
    num_of_uses = models.IntegerField('the number of times the tiny url was used', default=0)

    def __str__(self):
        return self.original_url

    def get_tiny_url(self):
        return get_tiny_url_page_url() + self.hash

djangoTinyURL/tinyurl/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, Http404, HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views import generic
from django.urls import reverse

from .models import MyUrl
from .hash import get_hash, get_hash_with_hashids


def get_most_frequently_used():
    return MyUrl.objects.order_by('-num_of_uses')


class IndexView(generic.ListView):
    template_name = 'tinyurl/index.html'
    context_object_name = 'most_frequently_used'

    # set of all MyUrls sorted by number of uses
    def get_queryset(self):
        return get_most_frequently_used()


def delete(request):
    # check if request has deleted_url_id
    try:
        deleted_id = request.POST['deleted_url_id']
    # if request hasn't deleted_url_id
    except KeyError:
        # go to the Index page with an error message
        return render(request, 'tinyurl/index.html', {
            'most_frequently_used': get_most_frequently_used(),
            'error_message': "You haven't selected anything to delete."
        })
    else:
        # check if DB has MyUrl with the given id
        deleted_my_url = MyUrl.objects.filter(id=deleted_id).first()
        # if DB hasn't MyUrl with the given id
        if deleted_my_url is None or deleted_my_url is []:
            return render(request, 'tinyurl/index.html', {
                'most_frequently_used': get_most_frequently_used(),
                'error_message': "You haven't selected anything to delete."
            })
        # if DB has MyUrl with the given id
        else:
            # delete MyUrl with the given id
            MyUrl.objects.filter(id=deleted_id).delete()
            # go to the Index page with an success message
            return render(request, 'tinyurl/index.html', {
                'most_frequently_used':  get_most_frequently_used(),
                'success_message': 'Tiny URL has been deleted successfully.'
            })


class DetailView(generic.DetailView):
    template_name = 'tinyurl/detail.html'
    model = MyUrl


# for GET method
# when you click on button to go to create page
def create(request):
    return render(request, 'tinyurl/create.html')


# for Post method
# when you click on button to send a form for generating tiny url
def create_post(request):
    try:
        original_url = request.POST['original_url']
    except KeyError:
        return render(request, 'tinyurl/create.html', {
                'error_message': "You didn't give me any url ;("
            })
    else:
        # if the original url is empty
        if original_url is None or original_url is '':
            return render(request, 'tinyurl/create.html', {
                'error_message': "You didn't give me any url ;("
            })
        else:
            # find this original url in DB
            duplicate_url = MyUrl.objects.filter(original_url=original_url).first()
            # if MyUrl with this original_url already exists
            if duplicate_url is not None:
                return render(request, 'tinyurl/create.html', {
                    'error_message': "I already made a tiny url for this one."
                })
            else:
                # generate a MyUrl
                my_url = MyUrl.objects.create(original_url=original_url, hash=0,
                                              pub_date=timezone.now(), last_us_date=timezone.now(), num_of_uses=0)
                # generate a hash for my_url
                my_url.hash = get_hash_with_hashids(my_url.id)
                # save the changes in DB
                my_url.save()
                # redirect to the detail page
                return redirect(reverse('tinyurl:detail', args=(my_url.id,)))


# redirects to the original url from the tiny url
def tiny_url(request, my_hash):
    my_url = MyUrl.objects.filter(hash=my_hash).first()
    # if MyUrl with the given hash doesn't exist
    if my_url is None:
        raise Http404("Page does not exist.")
    else:
        # increase number of uses
        my_url.num_of_uses = F('num_of_uses') + 1
        # update the last use date
        my_url.last_us_date = timezone.now()
        # save the changes in DB
        my_url.save()
        return redirect(my_url.original_url)

djangoTinyURL/tinyurl/templates/tinyurl/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'tinyurl/my_stylesheet.css' %}">
</head>
<body>
    <header><a href="{% url 'tinyurl:index' %}"><h1>Tiny URL</h1></a>
        <a href="{% url 'tinyurl:create' %}" class="button">Create new tiny url</a>
    </header>
    <div class="wholebody">
    {% if error_message %}<p><strong class="error_msg">{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'tinyurl:create_post'%}" method="post">
        {% csrf_token  %}
        <label>Please input your original url here:</label><br><br>
        <input type="text" name="original_url" onkeydown="this.style.width = ((this.value.length + 0) * 8) + 'px';" class="original_url_input" placeholder="type down your url..."><br>
        <div class="input-buffer"></div><br>
        <input type="submit" value="Create" class="create_button">
    </form>
    </div>
</body>
</html>

djangoTinyURL/tinyurl/templates/tinyurl/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tiny url: {{ myurl.id }}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'tinyurl/my_stylesheet.css' %}">
</head>
<body>
    <header><a href="{% url 'tinyurl:index' %}"><h1>Tiny URL</h1></a>
        <a href="{% url 'tinyurl:create' %}" class="button">Create new tiny url</a>
    </header>
    <div class="wholebody">
        <table border="0" class="detail_table">
            <tr>
                <td>Original url:</td>
                <td>{{ myurl.original_url }}</td>
            </tr>
            <tr>
                <td>Tiny url:</td>
                <td><div>{{ myurl.get_tiny_url }}</div></td>
            </tr>
            <tr>
                <td>Number of uses:</td>
                <td>{{ myurl.num_of_uses }}</td>
            </tr>
        </table>
    </div>
</body>
</html>

djangoTinyURL/tinyurl/templates/tinyurl/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tiny Url</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'tinyurl/my_stylesheet.css' %}">
</head>
<body>
    <header><a href="{% url 'tinyurl:index' %}"><h1>Tiny URL</h1></a>
        <a href="{% url 'tinyurl:create' %}" class="button" >Create new tiny url</a>
    </header>
    <div class="wholebody">
    {% if error_message %}<p><strong class="error_msg">{{ error_message }}</strong></p>{% endif %}
    {% if success_message %}<p><strong class="success_msg">{{ success_message }}</strong></p>{% endif %}
        {% if most_frequently_used %}
            <form action="{% url 'tinyurl:delete' %}" method="post">
                <table border="1" class="main_table">
                    <tr>
                        <th>Original url</th>
                        <th>Tiny url</th>
                        <th>Number of uses</th>
                        {% csrf_token %}
                        <th><input type="submit" value="Delete" class="delete_button"></th>
                    </tr>
                    {% for myurl in most_frequently_used %}
                        <tr>
                            <td><div><a href="{% url 'tinyurl:detail' myurl.id %}">{{ myurl.original_url }}</a></div></td>
                            <td><a href="{% url 'tinyurl:detail' myurl.id %}">{{ myurl.get_tiny_url }}</a></td>
                            <td><div class="p">{{ myurl.num_of_uses }}</div></td>
                            {% csrf_token %}
                            <td><div class="p"><input type="radio" name="deleted_url_id" id="{{ myurl.id }}" value="{{ myurl.id }}"></div></td>
                        </tr>
                    {% endfor %}
                </table>
            </form>
        {% else %}
            <p class="error_msg">No tiny url has been added.</p>
        {% endif %}
    </div>
</body>
</html>